services:
  - name: docker
    image: docker:17.10.0-ce-dind
    capabilities:
     - all
    pid: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /dev:/dev
     - /etc/resolv.conf:/etc/resolv.conf
     - /etc/os-release:/etc/os-release
     - /lib/modules:/lib/modules
     - /run:/run
     - /var:/var:rshared,rbind
     - /var/lib/kubeadm:/etc/kubernetes
     - /var/lib/cni/etc:/etc/cni:rshared,rbind
     - /var/lib/cni/opt:/opt/cni:rshared,rbind
     - /var/lib/kubelet-plugins:/usr/libexec/kubernetes/kubelet-plugins:rshared,rbind
    rootfsPropagation: shared
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
    runtime:
      mkdir: ["/var/lib/kubeadm", "/var/lib/cni/etc", "/var/lib/cni/opt", "/var/lib/kubelet-plugins"]
  - name: kubernetes-docker-image-cache-common
    image: linuxkitprojects/kubernetes-docker-image-cache-common:02d28e234458f29277f175e68fdca028403b3ed8
files:
  - path: /etc/kubelet.sh.conf
    contents: ""
