kernel:
  image: linuxkit/kernel:4.9.39
  cmdline: "console=tty0 console=ttyS0"
init:
  - linuxkit/init:4dcee04c04c900a5796dc719f8d16fea7e771059
  - linuxkit/runc:f5960b83a8766ae083efc744fa63dbf877450e4f
  - linuxkit/containerd:acd23f7c020e09799e03331e781f35965e19981f
  - linuxkit/ca-certificates:67acf038c44bb191ebb704ec7bb39a1524052cdf
onboot:
  - name: sysctl
    image: linuxkit/sysctl:d1a43c7c91e92374766f962dc8534cf9508756b0
  - name: sysfs
    image: linuxkit/sysfs:006a65b30cfdd9d751d7ab042fde7eca2c3bc9dc
  - name: binfmt
    image: linuxkit/binfmt:0bde4ebd422099f45c5ee03217413523ad2223e5
  - name: dhcpcd
    image: linuxkit/dhcpcd:17423c1ccced74e3c005fd80486e8177841fe02b
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:f5d4299909b159db35f72547e4ae70bd76c42c6c
  - name: format
    image: linuxkit/format:efafddf9bc6165b5efaf09c532c15a1100a10e61
  - name: mounts
    image: linuxkit/mount:54990a6a69cb3ead4da8a9c1f0b651e27aea8d3f
    command: ["/usr/bin/mountie", "/var/lib/"]
  - name: var
    image: library/alpine:3.6
    command: ["mkdir", "/var/lib/kubeadm"]
    binds:
      - /var/lib:/var/lib
services:
  - name: getty
    image: linuxkit/getty:894eef1e5f62f3bc31de8ffaff2b6c0e093c4595
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:1516d5d70683a5d925fe475eb1b6164a2f67ac3b
  - name: ntpd
    image: linuxkit/openntpd:2874b66c9fa51fa5b4d11c8b50441eb94ee22a5a
  - name: sshd
    image: linuxkit/sshd:dc98a72c1d1285c30f2db176252f3ce2bf645d5b
  - name: docker
    image: docker:17.06.0-ce-dind
    capabilities:
     - all
    pid: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /dev:/dev
     - /etc/resolv.conf:/etc/resolv.conf
     - /lib/modules:/lib/modules
     - /var:/var:rshared,rbind
     - /var/lib/kubeadm:/etc/kubernetes
     - /etc/cni:/etc/cni:rshared,rbind
     - /opt/cni:/opt/cni:rshared,rbind
    rootfsPropagation: shared
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
  - name: kubernetes-image-cache-common
    image: linuxkitprojects/kubernetes-image-cache-common:6fccda74ea301f9a62cdcfc2fe4952cff2c8c97b
  - name: kubernetes-image-cache-control-plane
    image: linuxkitprojects/kubernetes-image-cache-control-plane:6fccda74ea301f9a62cdcfc2fe4952cff2c8c97b
  - name: kubelet
    image: linuxkitprojects/kubernetes:8fca97c5faf0c6288aee82485d8c6539b84db256
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
  - {path: etc/cni, directory: true}
  - {path: opt/cni, directory: true}
