kernel:
  image: linuxkit/kernel:4.9.51
  cmdline: "console=tty0 console=ttyS0"
init:
  - linuxkit/init:7804129bd06218b72c298139a25698a748d253c6
  - linuxkit/runc:a1b564248a0d0b118c11e61db9f84ecf41dd2d2a
  - linuxkit/containerd:417f83f7b8dc1fa36acf90effe44f99c7397480a
  - linuxkit/ca-certificates:e44b0a66df5a102c0e220f0066b0d904710dcb10
onboot:
  - name: sysctl
    image: linuxkit/sysctl:154913b72c6f1f33eb408609fca9963628e8c051
    binds:
     - /etc/sysctl.d/01-kubernetes.conf:/etc/sysctl.d/01-kubernetes.conf
    readonly: false
  - name: sysfs
    image: linuxkit/sysfs:3ae01a25583ee37a5ff8b09a0e569cb4bd8cf2e9
  - name: dhcpcd
    image: linuxkit/dhcpcd:d4408777ed6b6e6e562a5d4938fd09804324b33e
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:da3138079c168e0c5608d8f3853366c113ed91d2
  - name: format
    image: linuxkit/format:158d992b7bf7ab984100c697d7e72161ea7d7382
  - name: mounts
    image: linuxkit/mount:4fe245efb01384e42622c36302e13e386bbaeb08
    command: ["/usr/bin/mountie", "/var/lib/"]
services:
  - name: getty
    image: linuxkit/getty:bf6872ce0a9f3ab519b3e502cc41ba3958bda2a6
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:558e86a36242bb74353bc9287b715ddb8567357e
  - name: ntpd
    image: linuxkit/openntpd:0d7befc79842849d0b88d6c3b64200e340d7cf67
  - name: sshd
    image: linuxkit/sshd:d313eea3d9d7fbcbc927d06a6700325725db2a82
  - name: kubelet
    image: linuxkitprojects/kubernetes:f3be02879f599ed59be5e307b866249e1a2f2eff
files:
  - path: etc/linuxkit.yml
    metadata: yaml
  - path: /etc/kubernetes
    symlink: "/var/lib/kubeadm"
  - path: /etc/kubeadm/kube-system.init/50-network.yaml
    source: network.yaml
  - path: /etc/sysctl.d/01-kubernetes.conf
    contents: 'net.ipv4.ip_forward = 1'
  - path: /opt/cni
    directory: true
  - path: /etc/cni
    directory: true
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
