kernel:
  image: "linuxkit/kernel:4.9.34"
  cmdline: "console=ttyS0 console=tty0 page_poison=1"
init:
  - linuxkit/init:36c56f0664d49c5a6adc1120d1bf5ba6ac30b389
  - linuxkit/runc:291131ec026430371e7c36165c3f43734fbc2541
  - linuxkit/containerd:1e3e8f207421de8deac8cedc26a138d6b1661a0d
  - linuxkit/ca-certificates:46b59484919bfa9af700e54e042048cb06261de4
onboot:
  - name: sysctl
    image: "linuxkit/sysctl:3aa6bc663c2849ef239be7d941d3eaf3e6fcc018"
  - name: sysfs
    image: linuxkit/sysfs:b4091d81261f4582ff899a8510110fc4f2be2b49
  - name: binfmt
    image: "linuxkit/binfmt:24e2b996f7d6ad20bfa9c9f1564a3c6172db47ce"
  - name: format
    image: "linuxkit/format:ba085fdcac31c383acee3b4b91d78eb7095e5ac3"
  - name: mounts
    image: "linuxkit/kubernetes:latest-mounts"
    capabilities:
     - all
    pid: host
    rootfsPropagation: shared
    binds:
     - /dev:/dev
     - /var:/var:rshared,rbind
services:
  - name: getty
    image: "linuxkit/getty:6d35e3fe138aaeaf099b5b4f31b3f12ba725cb49"
    env:
     - INSECURE=true
  - name: rngd
    image: "linuxkit/rngd:b50b22dd574c5377708977af769f053009fff6d5"
  - name: dhcpcd
    image: "linuxkit/dhcpcd:6c1ca76dbf808d5c27d10cbf22a8d4399be5c8ae"
  - name: ntpd
    image: "linuxkit/openntpd:a4c642d52e985922fcd97db52e471db123cc6841"
  - name: sshd
    image: "linuxkit/sshd:7535658a08a01c61e2851e4bc1f6346e89412de8"
  - name: docker
    image: "linuxkit/docker-ce:9e125aa533108731d11f6d7ec17aba6ded0cb4eb"
    capabilities:
     - all
    net: host
    pid: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /dev:/dev
     - /lib/modules:/lib/modules
     - /var:/var:rshared,rbind
     - /var/lib/kubeadm:/etc/kubernetes
     - /etc/cni:/etc/cni:rshared,rbind
     - /opt/cni:/opt/cni:rshared,rbind
    rootfsPropagation: shared
  - name: kubernetes-image-cache-common
    image: "linuxkit/kubernetes:latest-image-cache-common"
    binds:
      - /var/run:/var/run
  - name: kubelet
    image: "linuxkit/kubernetes:latest"
    capabilities:
     - all
    net: host
    pid: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /dev:/dev
     - /var:/var:rshared,rbind
     - /var/lib/kubeadm:/etc/kubernetes
     - /etc/cni:/rootfs/etc/cni:rshared,rbind
     - /opt/cni:/rootfs/opt/cni:rshared,rbind
    rootfsPropagation: shared
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
  - {path: etc/cni, directory: true}
  - {path: opt/cni, directory: true}
