kernel:
  image: "linuxkit/kernel:4.9.x"
  cmdline: "console=ttyS0 console=tty0 page_poison=1"
init:
  - linuxkit/init:63eed9ca7a09d2ce4c0c5e7238ac005fa44f564b
  - linuxkit/runc:b0fb122e10dbb7e4e45115177a61a3f8d68c19a9
  - linuxkit/containerd:18eaf72f3f4f9a9f29ca1951f66df701f873060b
  - linuxkit/ca-certificates:3344cdca1bc59fdfa17bd7f0fcbf491b9dbaa288
onboot:
  - name: sysctl
    image: "linuxkit/sysctl:1f5ec5d5e6f7a7a1b3d2ff9dd9e36fd6fb14756a"
    net: host
    pid: host
    ipc: host
    capabilities:
     - CAP_SYS_ADMIN
    readonly: true
  - name: sysfs
    image: linuxkit/sysfs:6c1d06f28ddd9681799d3950cddf044b930b221c
  - name: binfmt
    image: "linuxkit/binfmt:131026c0cf6084467316395fed3b358f64bda00c"
    binds:
     - /proc/sys/fs/binfmt_misc:/binfmt_misc
    readonly: true
  - name: format
    image: "linuxkit/format:d78093e943f9c88386e30c00353f9476d34fb551"
    binds:
     - /dev:/dev
    capabilities:
     - CAP_SYS_ADMIN
     - CAP_MKNOD
  - name: mounts
    image: "linuxkit/kubernetes:latest-mounts"
    capabilities:
     - all
    pid: host
    rootfsPropagation: shared
    binds:
     - /dev:/dev
     - /var:/var:rshared,rbind
services:
  - name: rngd
    image: "linuxkit/rngd:f5e5be43e730ea819c3293d5c6dcbfa7f4c5c314"
    capabilities:
     - CAP_SYS_ADMIN
    oomScoreAdj: -800
    readonly: true
  - name: dhcpcd
    image: "linuxkit/dhcpcd:2def74ab3f9233b4c09ebb196ba47c27c08b0ed8"
    binds:
     - /var:/var
     - /tmp/etc:/etc
    capabilities:
     - CAP_NET_ADMIN
     - CAP_NET_BIND_SERVICE
     - CAP_NET_RAW
    net: host
    oomScoreAdj: -800
  - name: ntpd
    image: "linuxkit/openntpd:a38eabb308d0405f58894979f8b8031a6c7e1134"
    capabilities:
      - CAP_SYS_TIME
      - CAP_SYS_NICE
      - CAP_SYS_CHROOT
      - CAP_SETUID
      - CAP_SETGID
    net: host
  - name: sshd
    image: "linuxkit/sshd:e108d208adf692c8a0954f602743e0eec445364e"
    capabilities:
     - all
    net: host
    pid: host
    binds:
     - /root/.ssh:/root/.ssh
  - name: docker
    image: "linuxkit/docker-ce:741bf21513328f674e0cdcaa55492b0b75974e08"
    capabilities:
     - all
    net: host
    pid: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /dev:/dev
     - /lib/modules:/lib/modules
     - /var:/var:rshared,rbind
     - /var/lib/kubeadm:/etc/kubernetes
     - /etc/cni:/etc/cni:rshared,rbind
     - /opt/cni:/opt/cni:rshared,rbind
    rootfsPropagation: shared
  - name: kubernetes-image-cache-common
    image: "linuxkit/kubernetes:latest-image-cache-common"
    binds:
      - /var/run:/var/run
  - name: kubelet
    image: "linuxkit/kubernetes:latest"
    capabilities:
     - all
    net: host
    pid: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /dev:/dev
     - /var:/var:rshared,rbind
     - /var/lib/kubeadm:/etc/kubernetes
     - /etc/cni:/rootfs/etc/cni:rshared,rbind
     - /opt/cni:/rootfs/opt/cni:rshared,rbind
    rootfsPropagation: shared
files:
  - path: root/.ssh/authorized_keys
    contents: '# Your ssh key goes here'
  - {path: etc/cni, directory: true}
  - {path: opt/cni, directory: true}
outputs:
  - format: kernel+initrd
