kernel:
  image: linuxkit/kernel:4.9.61
  cmdline: "console=tty0 console=ttyS0"
init:
  - linuxkit/init:42a92119e1ca10380e0d33e26c0cbcf85b9b3558
  - linuxkit/runc:1b0741d07949c0acc444cd6a04ee7f833443579d
  - linuxkit/containerd:bfb61cc1d26c39cd4b2bc08f7a9963fefa0ef3bf
  - linuxkit/ca-certificates:af4880e78edc28743f7c5e262678c67c6add4c26
onboot:
  - name: sysctl
    image: linuxkit/sysctl:a9ad57ed738a31ea9380cd73236866c312b35489
    binds:
     - /etc/sysctl.d/01-kubernetes.conf:/etc/sysctl.d/01-kubernetes.conf
    readonly: false
  - name: sysfs
    image: linuxkit/sysfs:5367b46211882278b84a9e8048855ca5df65beda
  - name: dhcpcd
    image: linuxkit/dhcpcd:48831507404049660b960e4055f544917d90378e
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: linuxkit/metadata:026aca5c08c22589a7e319f79449bef2c65f04c5
  - name: format
    image: linuxkit/format:10e75e78e1f134d310c62e9a0352df1c67b0dd81
  - name: mounts
    image: linuxkit/mount:41685ecc8039643948e5dff46e17584753469a7a
    command: ["/usr/bin/mountie", "/var/lib/"]
services:
  - name: getty
    image: linuxkit/getty:6af22c32c98536a79230eef000e9abd06b037faa
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:842e5e8ece7934f0cab9fd0027b595ff3471e5b9
  - name: ntpd
    image: linuxkit/openntpd:07a80c3e3e816658318ac027e1253ff9a228b8de
  - name: sshd
    image: linuxkit/sshd:b7f21ef1b13300a994e35eac3644e4f84f0ada8a
  - name: kubelet
    image: linuxkitprojects/kubelet:4f93f02fb13f8c3e98e922afb2ef8cd1e0da66b3
files:
  - path: etc/linuxkit.yml
    metadata: yaml
  - path: /etc/kubernetes
    symlink: "/var/lib/kubeadm"
  - path: /etc/os-release
    contents: |
      PRETTY_NAME="LinuxKit Kubernetes Project"
  - path: /usr/libexec/kubernetes/kubelet-plugins
    symlink: "/var/lib/kubelet-plugins"
  - path: /etc/kubeadm/
    directory: true
  - path: /etc/sysctl.d/01-kubernetes.conf
    contents: 'net.ipv4.ip_forward = 1'
  - path: /opt/cni
    directory: true
  - path: /etc/cni
    directory: true
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
